---
- name: upgrade package to the latest version via apt-get dist-upgrade
  sudo: yes
  sudo_user: root
  apt: upgrade=dist update_cache=yes cache_valid_time=3600
  ignore_errors: yes

- name: make sure required system packages are installed
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - locales
    - git
    - python
    - python-dev
    - python3-dev
    - python-pip
    - apt-transport-https
    - libmemcached-dev
    - graphviz
    - libjpeg-dev
